/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424754",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdcc6",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d8e3fb",
        "outline-variant": "#c2c6d6",
        "tertiary": "#924700",
        "on-error-container": "#93000a",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#e7eeff",
        "on-background": "#111c2d",
        "surface-bright": "#f9f9ff",
        "outline": "#727785",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004395",
        "on-error": "#ffffff",
        "secondary": "#505f76",
        "tertiary-fixed-dim": "#ffb786",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#adc6ff",
        "on-surface": "#111c2d",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fefcff",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-primary": "#adc6ff",
        "inverse-on-surface": "#ecf1ff",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-container": "#b75b00",
        "surface-dim": "#cfdaf2",
        "surface": "#f9f9ff",
        "secondary-container": "#d0e1fb",
        "primary": "#0058be",
        "background": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "error": "#ba1a1a",
        "surface-variant": "#d8e3fb",
        "on-tertiary-fixed": "#311400",
        "inverse-surface": "#263143",
        "on-tertiary-fixed-variant": "#723600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-gap": "32px",
        "element-gap-md": "16px",
        "element-gap-sm": "8px",
        gutter: "16px",
        "container-padding": "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  darkMode: "class",
  plugins: [],
}
